package com.sysdt.lock.dao;

import com.sysdt.lock.model.ClienteServicio;
import com.sysdt.lock.model.ClienteServicioExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ClienteServicioMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cliente_servicio
     *
     * @mbggenerated Mon May 01 19:47:25 CDT 2017
     */
    int countByExample(ClienteServicioExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cliente_servicio
     *
     * @mbggenerated Mon May 01 19:47:25 CDT 2017
     */
    int deleteByExample(ClienteServicioExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cliente_servicio
     *
     * @mbggenerated Mon May 01 19:47:25 CDT 2017
     */
    int insert(ClienteServicio record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cliente_servicio
     *
     * @mbggenerated Mon May 01 19:47:25 CDT 2017
     */
    int insertSelective(ClienteServicio record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cliente_servicio
     *
     * @mbggenerated Mon May 01 19:47:25 CDT 2017
     */
    List<ClienteServicio> selectByExample(ClienteServicioExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cliente_servicio
     *
     * @mbggenerated Mon May 01 19:47:25 CDT 2017
     */
    int updateByExampleSelective(@Param("record") ClienteServicio record, @Param("example") ClienteServicioExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cliente_servicio
     *
     * @mbggenerated Mon May 01 19:47:25 CDT 2017
     */
    int updateByExample(@Param("record") ClienteServicio record, @Param("example") ClienteServicioExample example);
}