package com.sysdt.lock.dao;

import com.sysdt.lock.model.SupervisorEntidad;
import com.sysdt.lock.model.SupervisorEntidadExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SupervisorEntidadMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supervisor_entidad
     *
     * @mbggenerated Mon May 01 19:47:25 CDT 2017
     */
    int countByExample(SupervisorEntidadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supervisor_entidad
     *
     * @mbggenerated Mon May 01 19:47:25 CDT 2017
     */
    int deleteByExample(SupervisorEntidadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supervisor_entidad
     *
     * @mbggenerated Mon May 01 19:47:25 CDT 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supervisor_entidad
     *
     * @mbggenerated Mon May 01 19:47:25 CDT 2017
     */
    int insert(SupervisorEntidad record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supervisor_entidad
     *
     * @mbggenerated Mon May 01 19:47:25 CDT 2017
     */
    int insertSelective(SupervisorEntidad record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supervisor_entidad
     *
     * @mbggenerated Mon May 01 19:47:25 CDT 2017
     */
    List<SupervisorEntidad> selectByExample(SupervisorEntidadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supervisor_entidad
     *
     * @mbggenerated Mon May 01 19:47:25 CDT 2017
     */
    SupervisorEntidad selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supervisor_entidad
     *
     * @mbggenerated Mon May 01 19:47:25 CDT 2017
     */
    int updateByExampleSelective(@Param("record") SupervisorEntidad record, @Param("example") SupervisorEntidadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supervisor_entidad
     *
     * @mbggenerated Mon May 01 19:47:25 CDT 2017
     */
    int updateByExample(@Param("record") SupervisorEntidad record, @Param("example") SupervisorEntidadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supervisor_entidad
     *
     * @mbggenerated Mon May 01 19:47:25 CDT 2017
     */
    int updateByPrimaryKeySelective(SupervisorEntidad record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supervisor_entidad
     *
     * @mbggenerated Mon May 01 19:47:25 CDT 2017
     */
    int updateByPrimaryKey(SupervisorEntidad record);
}