package com.sysdt.lock.dao;

import com.sysdt.lock.model.TipoServicio;
import com.sysdt.lock.model.TipoServicioExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TipoServicioMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tipo_servicio
     *
     * @mbggenerated Mon May 01 19:47:25 CDT 2017
     */
    int countByExample(TipoServicioExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tipo_servicio
     *
     * @mbggenerated Mon May 01 19:47:25 CDT 2017
     */
    int deleteByExample(TipoServicioExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tipo_servicio
     *
     * @mbggenerated Mon May 01 19:47:25 CDT 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tipo_servicio
     *
     * @mbggenerated Mon May 01 19:47:25 CDT 2017
     */
    int insert(TipoServicio record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tipo_servicio
     *
     * @mbggenerated Mon May 01 19:47:25 CDT 2017
     */
    int insertSelective(TipoServicio record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tipo_servicio
     *
     * @mbggenerated Mon May 01 19:47:25 CDT 2017
     */
    List<TipoServicio> selectByExample(TipoServicioExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tipo_servicio
     *
     * @mbggenerated Mon May 01 19:47:25 CDT 2017
     */
    TipoServicio selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tipo_servicio
     *
     * @mbggenerated Mon May 01 19:47:25 CDT 2017
     */
    int updateByExampleSelective(@Param("record") TipoServicio record, @Param("example") TipoServicioExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tipo_servicio
     *
     * @mbggenerated Mon May 01 19:47:25 CDT 2017
     */
    int updateByExample(@Param("record") TipoServicio record, @Param("example") TipoServicioExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tipo_servicio
     *
     * @mbggenerated Mon May 01 19:47:25 CDT 2017
     */
    int updateByPrimaryKeySelective(TipoServicio record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tipo_servicio
     *
     * @mbggenerated Mon May 01 19:47:25 CDT 2017
     */
    int updateByPrimaryKey(TipoServicio record);
}