package com.sysdt.lock.dao;

import com.sysdt.lock.model.TipoEntidad;
import com.sysdt.lock.model.TipoEntidadExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TipoEntidadMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tipo_entidad
     *
     * @mbggenerated Mon May 01 19:47:25 CDT 2017
     */
    int countByExample(TipoEntidadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tipo_entidad
     *
     * @mbggenerated Mon May 01 19:47:25 CDT 2017
     */
    int deleteByExample(TipoEntidadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tipo_entidad
     *
     * @mbggenerated Mon May 01 19:47:25 CDT 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tipo_entidad
     *
     * @mbggenerated Mon May 01 19:47:25 CDT 2017
     */
    int insert(TipoEntidad record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tipo_entidad
     *
     * @mbggenerated Mon May 01 19:47:25 CDT 2017
     */
    int insertSelective(TipoEntidad record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tipo_entidad
     *
     * @mbggenerated Mon May 01 19:47:25 CDT 2017
     */
    List<TipoEntidad> selectByExample(TipoEntidadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tipo_entidad
     *
     * @mbggenerated Mon May 01 19:47:25 CDT 2017
     */
    TipoEntidad selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tipo_entidad
     *
     * @mbggenerated Mon May 01 19:47:25 CDT 2017
     */
    int updateByExampleSelective(@Param("record") TipoEntidad record, @Param("example") TipoEntidadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tipo_entidad
     *
     * @mbggenerated Mon May 01 19:47:25 CDT 2017
     */
    int updateByExample(@Param("record") TipoEntidad record, @Param("example") TipoEntidadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tipo_entidad
     *
     * @mbggenerated Mon May 01 19:47:25 CDT 2017
     */
    int updateByPrimaryKeySelective(TipoEntidad record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tipo_entidad
     *
     * @mbggenerated Mon May 01 19:47:25 CDT 2017
     */
    int updateByPrimaryKey(TipoEntidad record);
}