package com.sysdt.lock.model;

public class Chofer {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chofer.id
     *
     * @mbggenerated Mon May 01 19:47:25 CDT 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chofer.nombre
     *
     * @mbggenerated Mon May 01 19:47:25 CDT 2017
     */
    private String nombre;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chofer.apaterno
     *
     * @mbggenerated Mon May 01 19:47:25 CDT 2017
     */
    private String apaterno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chofer.amaterno
     *
     * @mbggenerated Mon May 01 19:47:25 CDT 2017
     */
    private String amaterno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chofer.token
     *
     * @mbggenerated Mon May 01 19:47:25 CDT 2017
     */
    private String token;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chofer.enabled
     *
     * @mbggenerated Mon May 01 19:47:25 CDT 2017
     */
    private Boolean enabled;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chofer.idCliente
     *
     * @mbggenerated Mon May 01 19:47:25 CDT 2017
     */
    private Integer idcliente;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chofer.id
     *
     * @return the value of chofer.id
     *
     * @mbggenerated Mon May 01 19:47:25 CDT 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chofer.id
     *
     * @param id the value for chofer.id
     *
     * @mbggenerated Mon May 01 19:47:25 CDT 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chofer.nombre
     *
     * @return the value of chofer.nombre
     *
     * @mbggenerated Mon May 01 19:47:25 CDT 2017
     */
    public String getNombre() {
        return nombre;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chofer.nombre
     *
     * @param nombre the value for chofer.nombre
     *
     * @mbggenerated Mon May 01 19:47:25 CDT 2017
     */
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chofer.apaterno
     *
     * @return the value of chofer.apaterno
     *
     * @mbggenerated Mon May 01 19:47:25 CDT 2017
     */
    public String getApaterno() {
        return apaterno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chofer.apaterno
     *
     * @param apaterno the value for chofer.apaterno
     *
     * @mbggenerated Mon May 01 19:47:25 CDT 2017
     */
    public void setApaterno(String apaterno) {
        this.apaterno = apaterno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chofer.amaterno
     *
     * @return the value of chofer.amaterno
     *
     * @mbggenerated Mon May 01 19:47:25 CDT 2017
     */
    public String getAmaterno() {
        return amaterno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chofer.amaterno
     *
     * @param amaterno the value for chofer.amaterno
     *
     * @mbggenerated Mon May 01 19:47:25 CDT 2017
     */
    public void setAmaterno(String amaterno) {
        this.amaterno = amaterno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chofer.token
     *
     * @return the value of chofer.token
     *
     * @mbggenerated Mon May 01 19:47:25 CDT 2017
     */
    public String getToken() {
        return token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chofer.token
     *
     * @param token the value for chofer.token
     *
     * @mbggenerated Mon May 01 19:47:25 CDT 2017
     */
    public void setToken(String token) {
        this.token = token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chofer.enabled
     *
     * @return the value of chofer.enabled
     *
     * @mbggenerated Mon May 01 19:47:25 CDT 2017
     */
    public Boolean getEnabled() {
        return enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chofer.enabled
     *
     * @param enabled the value for chofer.enabled
     *
     * @mbggenerated Mon May 01 19:47:25 CDT 2017
     */
    public void setEnabled(Boolean enabled) {
        this.enabled = enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chofer.idCliente
     *
     * @return the value of chofer.idCliente
     *
     * @mbggenerated Mon May 01 19:47:25 CDT 2017
     */
    public Integer getIdcliente() {
        return idcliente;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chofer.idCliente
     *
     * @param idcliente the value for chofer.idCliente
     *
     * @mbggenerated Mon May 01 19:47:25 CDT 2017
     */
    public void setIdcliente(Integer idcliente) {
        this.idcliente = idcliente;
    }
}