package com.sysdt.lock.model;

public class ClienteServicio {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cliente_servicio.idCliente
     *
     * @mbggenerated Mon May 01 19:47:25 CDT 2017
     */
    private Integer idcliente;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cliente_servicio.idServicio
     *
     * @mbggenerated Mon May 01 19:47:25 CDT 2017
     */
    private Integer idservicio;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cliente_servicio.idCliente
     *
     * @return the value of cliente_servicio.idCliente
     *
     * @mbggenerated Mon May 01 19:47:25 CDT 2017
     */
    public Integer getIdcliente() {
        return idcliente;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cliente_servicio.idCliente
     *
     * @param idcliente the value for cliente_servicio.idCliente
     *
     * @mbggenerated Mon May 01 19:47:25 CDT 2017
     */
    public void setIdcliente(Integer idcliente) {
        this.idcliente = idcliente;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cliente_servicio.idServicio
     *
     * @return the value of cliente_servicio.idServicio
     *
     * @mbggenerated Mon May 01 19:47:25 CDT 2017
     */
    public Integer getIdservicio() {
        return idservicio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cliente_servicio.idServicio
     *
     * @param idservicio the value for cliente_servicio.idServicio
     *
     * @mbggenerated Mon May 01 19:47:25 CDT 2017
     */
    public void setIdservicio(Integer idservicio) {
        this.idservicio = idservicio;
    }
}