package com.sysdt.lock.model;

public class Cliente {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cliente.id
     *
     * @mbggenerated Sat Aug 26 16:05:21 CDT 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cliente.nombre
     *
     * @mbggenerated Sat Aug 26 16:05:21 CDT 2017
     */
    private String nombre;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cliente.logo
     *
     * @mbggenerated Sat Aug 26 16:05:21 CDT 2017
     */
    private String logo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cliente.ancho
     *
     * @mbggenerated Sat Aug 26 16:05:21 CDT 2017
     */
    private Integer ancho;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cliente.alto
     *
     * @mbggenerated Sat Aug 26 16:05:21 CDT 2017
     */
    private String alto;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cliente.isWialon
     *
     * @mbggenerated Sat Aug 26 16:05:21 CDT 2017
     */
    private Boolean iswialon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cliente.periodoValidacion
     *
     * @mbggenerated Sat Aug 26 16:05:21 CDT 2017
     */
    private Integer periodovalidacion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cliente.maxOperadores
     *
     * @mbggenerated Sat Aug 26 16:05:21 CDT 2017
     */
    private Integer maxoperadores;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cliente.maxUnidades
     *
     * @mbggenerated Sat Aug 26 16:05:21 CDT 2017
     */
    private Integer maxunidades;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cliente.maxChoferes
     *
     * @mbggenerated Sat Aug 26 16:05:21 CDT 2017
     */
    private Integer maxchoferes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cliente.maxSupervisores
     *
     * @mbggenerated Sat Aug 26 16:05:21 CDT 2017
     */
    private Integer maxsupervisores;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cliente.maxMasters
     *
     * @mbggenerated Sat Aug 26 16:05:21 CDT 2017
     */
    private Integer maxmasters;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cliente.id
     *
     * @return the value of cliente.id
     *
     * @mbggenerated Sat Aug 26 16:05:21 CDT 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cliente.id
     *
     * @param id the value for cliente.id
     *
     * @mbggenerated Sat Aug 26 16:05:21 CDT 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cliente.nombre
     *
     * @return the value of cliente.nombre
     *
     * @mbggenerated Sat Aug 26 16:05:21 CDT 2017
     */
    public String getNombre() {
        return nombre;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cliente.nombre
     *
     * @param nombre the value for cliente.nombre
     *
     * @mbggenerated Sat Aug 26 16:05:21 CDT 2017
     */
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cliente.logo
     *
     * @return the value of cliente.logo
     *
     * @mbggenerated Sat Aug 26 16:05:21 CDT 2017
     */
    public String getLogo() {
        return logo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cliente.logo
     *
     * @param logo the value for cliente.logo
     *
     * @mbggenerated Sat Aug 26 16:05:21 CDT 2017
     */
    public void setLogo(String logo) {
        this.logo = logo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cliente.ancho
     *
     * @return the value of cliente.ancho
     *
     * @mbggenerated Sat Aug 26 16:05:21 CDT 2017
     */
    public Integer getAncho() {
        return ancho;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cliente.ancho
     *
     * @param ancho the value for cliente.ancho
     *
     * @mbggenerated Sat Aug 26 16:05:21 CDT 2017
     */
    public void setAncho(Integer ancho) {
        this.ancho = ancho;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cliente.alto
     *
     * @return the value of cliente.alto
     *
     * @mbggenerated Sat Aug 26 16:05:21 CDT 2017
     */
    public String getAlto() {
        return alto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cliente.alto
     *
     * @param alto the value for cliente.alto
     *
     * @mbggenerated Sat Aug 26 16:05:21 CDT 2017
     */
    public void setAlto(String alto) {
        this.alto = alto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cliente.isWialon
     *
     * @return the value of cliente.isWialon
     *
     * @mbggenerated Sat Aug 26 16:05:21 CDT 2017
     */
    public Boolean getIswialon() {
        return iswialon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cliente.isWialon
     *
     * @param iswialon the value for cliente.isWialon
     *
     * @mbggenerated Sat Aug 26 16:05:21 CDT 2017
     */
    public void setIswialon(Boolean iswialon) {
        this.iswialon = iswialon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cliente.periodoValidacion
     *
     * @return the value of cliente.periodoValidacion
     *
     * @mbggenerated Sat Aug 26 16:05:21 CDT 2017
     */
    public Integer getPeriodovalidacion() {
        return periodovalidacion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cliente.periodoValidacion
     *
     * @param periodovalidacion the value for cliente.periodoValidacion
     *
     * @mbggenerated Sat Aug 26 16:05:21 CDT 2017
     */
    public void setPeriodovalidacion(Integer periodovalidacion) {
        this.periodovalidacion = periodovalidacion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cliente.maxOperadores
     *
     * @return the value of cliente.maxOperadores
     *
     * @mbggenerated Sat Aug 26 16:05:21 CDT 2017
     */
    public Integer getMaxoperadores() {
        return maxoperadores;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cliente.maxOperadores
     *
     * @param maxoperadores the value for cliente.maxOperadores
     *
     * @mbggenerated Sat Aug 26 16:05:21 CDT 2017
     */
    public void setMaxoperadores(Integer maxoperadores) {
        this.maxoperadores = maxoperadores;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cliente.maxUnidades
     *
     * @return the value of cliente.maxUnidades
     *
     * @mbggenerated Sat Aug 26 16:05:21 CDT 2017
     */
    public Integer getMaxunidades() {
        return maxunidades;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cliente.maxUnidades
     *
     * @param maxunidades the value for cliente.maxUnidades
     *
     * @mbggenerated Sat Aug 26 16:05:21 CDT 2017
     */
    public void setMaxunidades(Integer maxunidades) {
        this.maxunidades = maxunidades;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cliente.maxChoferes
     *
     * @return the value of cliente.maxChoferes
     *
     * @mbggenerated Sat Aug 26 16:05:21 CDT 2017
     */
    public Integer getMaxchoferes() {
        return maxchoferes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cliente.maxChoferes
     *
     * @param maxchoferes the value for cliente.maxChoferes
     *
     * @mbggenerated Sat Aug 26 16:05:21 CDT 2017
     */
    public void setMaxchoferes(Integer maxchoferes) {
        this.maxchoferes = maxchoferes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cliente.maxSupervisores
     *
     * @return the value of cliente.maxSupervisores
     *
     * @mbggenerated Sat Aug 26 16:05:21 CDT 2017
     */
    public Integer getMaxsupervisores() {
        return maxsupervisores;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cliente.maxSupervisores
     *
     * @param maxsupervisores the value for cliente.maxSupervisores
     *
     * @mbggenerated Sat Aug 26 16:05:21 CDT 2017
     */
    public void setMaxsupervisores(Integer maxsupervisores) {
        this.maxsupervisores = maxsupervisores;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cliente.maxMasters
     *
     * @return the value of cliente.maxMasters
     *
     * @mbggenerated Sat Aug 26 16:05:21 CDT 2017
     */
    public Integer getMaxmasters() {
        return maxmasters;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cliente.maxMasters
     *
     * @param maxmasters the value for cliente.maxMasters
     *
     * @mbggenerated Sat Aug 26 16:05:21 CDT 2017
     */
    public void setMaxmasters(Integer maxmasters) {
        this.maxmasters = maxmasters;
    }
}