package com.sysdt.lock.model;

public class Email {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column email.id
     *
     * @mbggenerated Fri Apr 14 21:13:50 CDT 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column email.direccion
     *
     * @mbggenerated Fri Apr 14 21:13:50 CDT 2017
     */
    private String direccion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column email.username
     *
     * @mbggenerated Fri Apr 14 21:13:50 CDT 2017
     */
    private String username;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column email.id
     *
     * @return the value of email.id
     *
     * @mbggenerated Fri Apr 14 21:13:50 CDT 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column email.id
     *
     * @param id the value for email.id
     *
     * @mbggenerated Fri Apr 14 21:13:50 CDT 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column email.direccion
     *
     * @return the value of email.direccion
     *
     * @mbggenerated Fri Apr 14 21:13:50 CDT 2017
     */
    public String getDireccion() {
        return direccion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column email.direccion
     *
     * @param direccion the value for email.direccion
     *
     * @mbggenerated Fri Apr 14 21:13:50 CDT 2017
     */
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column email.username
     *
     * @return the value of email.username
     *
     * @mbggenerated Fri Apr 14 21:13:50 CDT 2017
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column email.username
     *
     * @param username the value for email.username
     *
     * @mbggenerated Fri Apr 14 21:13:50 CDT 2017
     */
    public void setUsername(String username) {
        this.username = username;
    }
}