package com.sysdt.lock.model;

import java.util.Date;

public class Historico {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column historico.id
     *
     * @mbggenerated Sat Feb 04 18:09:03 CST 2017
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column historico.username
     *
     * @mbggenerated Sat Feb 04 18:09:03 CST 2017
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column historico.fecha
     *
     * @mbggenerated Sat Feb 04 18:09:03 CST 2017
     */
    private Date fecha;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column historico.placas_eco
     *
     * @mbggenerated Sat Feb 04 18:09:03 CST 2017
     */
    private String placasEco;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column historico.estado
     *
     * @mbggenerated Sat Feb 04 18:09:03 CST 2017
     */
    private Boolean estado;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column historico.latitud
     *
     * @mbggenerated Sat Feb 04 18:09:03 CST 2017
     */
    private String latitud;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column historico.longitud
     *
     * @mbggenerated Sat Feb 04 18:09:03 CST 2017
     */
    private String longitud;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column historico.idTipoEvento
     *
     * @mbggenerated Sat Feb 04 18:09:03 CST 2017
     */
    private Integer idtipoevento;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column historico.idChofer
     *
     * @mbggenerated Sat Feb 04 18:09:03 CST 2017
     */
    private Integer idchofer;
    
    private String chofer;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column historico.id
     *
     * @return the value of historico.id
     *
     * @mbggenerated Sat Feb 04 18:09:03 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column historico.id
     *
     * @param id the value for historico.id
     *
     * @mbggenerated Sat Feb 04 18:09:03 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column historico.username
     *
     * @return the value of historico.username
     *
     * @mbggenerated Sat Feb 04 18:09:03 CST 2017
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column historico.username
     *
     * @param username the value for historico.username
     *
     * @mbggenerated Sat Feb 04 18:09:03 CST 2017
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column historico.fecha
     *
     * @return the value of historico.fecha
     *
     * @mbggenerated Sat Feb 04 18:09:03 CST 2017
     */
    public Date getFecha() {
        return fecha;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column historico.fecha
     *
     * @param fecha the value for historico.fecha
     *
     * @mbggenerated Sat Feb 04 18:09:03 CST 2017
     */
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column historico.placas_eco
     *
     * @return the value of historico.placas_eco
     *
     * @mbggenerated Sat Feb 04 18:09:03 CST 2017
     */
    public String getPlacasEco() {
        return placasEco;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column historico.placas_eco
     *
     * @param placasEco the value for historico.placas_eco
     *
     * @mbggenerated Sat Feb 04 18:09:03 CST 2017
     */
    public void setPlacasEco(String placasEco) {
        this.placasEco = placasEco;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column historico.estado
     *
     * @return the value of historico.estado
     *
     * @mbggenerated Sat Feb 04 18:09:03 CST 2017
     */
    public Boolean getEstado() {
        return estado;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column historico.estado
     *
     * @param estado the value for historico.estado
     *
     * @mbggenerated Sat Feb 04 18:09:03 CST 2017
     */
    public void setEstado(Boolean estado) {
        this.estado = estado;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column historico.latitud
     *
     * @return the value of historico.latitud
     *
     * @mbggenerated Sat Feb 04 18:09:03 CST 2017
     */
    public String getLatitud() {
        return latitud;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column historico.latitud
     *
     * @param latitud the value for historico.latitud
     *
     * @mbggenerated Sat Feb 04 18:09:03 CST 2017
     */
    public void setLatitud(String latitud) {
        this.latitud = latitud;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column historico.longitud
     *
     * @return the value of historico.longitud
     *
     * @mbggenerated Sat Feb 04 18:09:03 CST 2017
     */
    public String getLongitud() {
        return longitud;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column historico.longitud
     *
     * @param longitud the value for historico.longitud
     *
     * @mbggenerated Sat Feb 04 18:09:03 CST 2017
     */
    public void setLongitud(String longitud) {
        this.longitud = longitud;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column historico.idTipoEvento
     *
     * @return the value of historico.idTipoEvento
     *
     * @mbggenerated Sat Feb 04 18:09:03 CST 2017
     */
    public Integer getIdtipoevento() {
        return idtipoevento;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column historico.idTipoEvento
     *
     * @param idtipoevento the value for historico.idTipoEvento
     *
     * @mbggenerated Sat Feb 04 18:09:03 CST 2017
     */
    public void setIdtipoevento(Integer idtipoevento) {
        this.idtipoevento = idtipoevento;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column historico.idChofer
     *
     * @return the value of historico.idChofer
     *
     * @mbggenerated Sat Feb 04 18:09:03 CST 2017
     */
    public Integer getIdchofer() {
        return idchofer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column historico.idChofer
     *
     * @param idchofer the value for historico.idChofer
     *
     * @mbggenerated Sat Feb 04 18:09:03 CST 2017
     */
    public void setIdchofer(Integer idchofer) {
        this.idchofer = idchofer;
    }

	public String getChofer() {
		return chofer;
	}

	public void setChofer(String chofer) {
		this.chofer = chofer;
	}
}