package com.sysdt.lock.model;

import java.util.ArrayList;
import java.util.List;

public class SupervisorEntidadExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table supervisor_entidad
     *
     * @mbggenerated Mon May 01 19:47:25 CDT 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table supervisor_entidad
     *
     * @mbggenerated Mon May 01 19:47:25 CDT 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table supervisor_entidad
     *
     * @mbggenerated Mon May 01 19:47:25 CDT 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supervisor_entidad
     *
     * @mbggenerated Mon May 01 19:47:25 CDT 2017
     */
    public SupervisorEntidadExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supervisor_entidad
     *
     * @mbggenerated Mon May 01 19:47:25 CDT 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supervisor_entidad
     *
     * @mbggenerated Mon May 01 19:47:25 CDT 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supervisor_entidad
     *
     * @mbggenerated Mon May 01 19:47:25 CDT 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supervisor_entidad
     *
     * @mbggenerated Mon May 01 19:47:25 CDT 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supervisor_entidad
     *
     * @mbggenerated Mon May 01 19:47:25 CDT 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supervisor_entidad
     *
     * @mbggenerated Mon May 01 19:47:25 CDT 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supervisor_entidad
     *
     * @mbggenerated Mon May 01 19:47:25 CDT 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supervisor_entidad
     *
     * @mbggenerated Mon May 01 19:47:25 CDT 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supervisor_entidad
     *
     * @mbggenerated Mon May 01 19:47:25 CDT 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supervisor_entidad
     *
     * @mbggenerated Mon May 01 19:47:25 CDT 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table supervisor_entidad
     *
     * @mbggenerated Mon May 01 19:47:25 CDT 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdtipousuarioIsNull() {
            addCriterion("idTipoUsuario is null");
            return (Criteria) this;
        }

        public Criteria andIdtipousuarioIsNotNull() {
            addCriterion("idTipoUsuario is not null");
            return (Criteria) this;
        }

        public Criteria andIdtipousuarioEqualTo(Integer value) {
            addCriterion("idTipoUsuario =", value, "idtipousuario");
            return (Criteria) this;
        }

        public Criteria andIdtipousuarioNotEqualTo(Integer value) {
            addCriterion("idTipoUsuario <>", value, "idtipousuario");
            return (Criteria) this;
        }

        public Criteria andIdtipousuarioGreaterThan(Integer value) {
            addCriterion("idTipoUsuario >", value, "idtipousuario");
            return (Criteria) this;
        }

        public Criteria andIdtipousuarioGreaterThanOrEqualTo(Integer value) {
            addCriterion("idTipoUsuario >=", value, "idtipousuario");
            return (Criteria) this;
        }

        public Criteria andIdtipousuarioLessThan(Integer value) {
            addCriterion("idTipoUsuario <", value, "idtipousuario");
            return (Criteria) this;
        }

        public Criteria andIdtipousuarioLessThanOrEqualTo(Integer value) {
            addCriterion("idTipoUsuario <=", value, "idtipousuario");
            return (Criteria) this;
        }

        public Criteria andIdtipousuarioIn(List<Integer> values) {
            addCriterion("idTipoUsuario in", values, "idtipousuario");
            return (Criteria) this;
        }

        public Criteria andIdtipousuarioNotIn(List<Integer> values) {
            addCriterion("idTipoUsuario not in", values, "idtipousuario");
            return (Criteria) this;
        }

        public Criteria andIdtipousuarioBetween(Integer value1, Integer value2) {
            addCriterion("idTipoUsuario between", value1, value2, "idtipousuario");
            return (Criteria) this;
        }

        public Criteria andIdtipousuarioNotBetween(Integer value1, Integer value2) {
            addCriterion("idTipoUsuario not between", value1, value2, "idtipousuario");
            return (Criteria) this;
        }

        public Criteria andUsernameIsNull() {
            addCriterion("username is null");
            return (Criteria) this;
        }

        public Criteria andUsernameIsNotNull() {
            addCriterion("username is not null");
            return (Criteria) this;
        }

        public Criteria andUsernameEqualTo(String value) {
            addCriterion("username =", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameNotEqualTo(String value) {
            addCriterion("username <>", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameGreaterThan(String value) {
            addCriterion("username >", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameGreaterThanOrEqualTo(String value) {
            addCriterion("username >=", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameLessThan(String value) {
            addCriterion("username <", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameLessThanOrEqualTo(String value) {
            addCriterion("username <=", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameLike(String value) {
            addCriterion("username like", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameNotLike(String value) {
            addCriterion("username not like", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameIn(List<String> values) {
            addCriterion("username in", values, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameNotIn(List<String> values) {
            addCriterion("username not in", values, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameBetween(String value1, String value2) {
            addCriterion("username between", value1, value2, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameNotBetween(String value1, String value2) {
            addCriterion("username not between", value1, value2, "username");
            return (Criteria) this;
        }

        public Criteria andIdtipoentidadIsNull() {
            addCriterion("idTipoEntidad is null");
            return (Criteria) this;
        }

        public Criteria andIdtipoentidadIsNotNull() {
            addCriterion("idTipoEntidad is not null");
            return (Criteria) this;
        }

        public Criteria andIdtipoentidadEqualTo(Integer value) {
            addCriterion("idTipoEntidad =", value, "idtipoentidad");
            return (Criteria) this;
        }

        public Criteria andIdtipoentidadNotEqualTo(Integer value) {
            addCriterion("idTipoEntidad <>", value, "idtipoentidad");
            return (Criteria) this;
        }

        public Criteria andIdtipoentidadGreaterThan(Integer value) {
            addCriterion("idTipoEntidad >", value, "idtipoentidad");
            return (Criteria) this;
        }

        public Criteria andIdtipoentidadGreaterThanOrEqualTo(Integer value) {
            addCriterion("idTipoEntidad >=", value, "idtipoentidad");
            return (Criteria) this;
        }

        public Criteria andIdtipoentidadLessThan(Integer value) {
            addCriterion("idTipoEntidad <", value, "idtipoentidad");
            return (Criteria) this;
        }

        public Criteria andIdtipoentidadLessThanOrEqualTo(Integer value) {
            addCriterion("idTipoEntidad <=", value, "idtipoentidad");
            return (Criteria) this;
        }

        public Criteria andIdtipoentidadIn(List<Integer> values) {
            addCriterion("idTipoEntidad in", values, "idtipoentidad");
            return (Criteria) this;
        }

        public Criteria andIdtipoentidadNotIn(List<Integer> values) {
            addCriterion("idTipoEntidad not in", values, "idtipoentidad");
            return (Criteria) this;
        }

        public Criteria andIdtipoentidadBetween(Integer value1, Integer value2) {
            addCriterion("idTipoEntidad between", value1, value2, "idtipoentidad");
            return (Criteria) this;
        }

        public Criteria andIdtipoentidadNotBetween(Integer value1, Integer value2) {
            addCriterion("idTipoEntidad not between", value1, value2, "idtipoentidad");
            return (Criteria) this;
        }

        public Criteria andIdentidadIsNull() {
            addCriterion("idEntidad is null");
            return (Criteria) this;
        }

        public Criteria andIdentidadIsNotNull() {
            addCriterion("idEntidad is not null");
            return (Criteria) this;
        }

        public Criteria andIdentidadEqualTo(String value) {
            addCriterion("idEntidad =", value, "identidad");
            return (Criteria) this;
        }

        public Criteria andIdentidadNotEqualTo(String value) {
            addCriterion("idEntidad <>", value, "identidad");
            return (Criteria) this;
        }

        public Criteria andIdentidadGreaterThan(String value) {
            addCriterion("idEntidad >", value, "identidad");
            return (Criteria) this;
        }

        public Criteria andIdentidadGreaterThanOrEqualTo(String value) {
            addCriterion("idEntidad >=", value, "identidad");
            return (Criteria) this;
        }

        public Criteria andIdentidadLessThan(String value) {
            addCriterion("idEntidad <", value, "identidad");
            return (Criteria) this;
        }

        public Criteria andIdentidadLessThanOrEqualTo(String value) {
            addCriterion("idEntidad <=", value, "identidad");
            return (Criteria) this;
        }

        public Criteria andIdentidadLike(String value) {
            addCriterion("idEntidad like", value, "identidad");
            return (Criteria) this;
        }

        public Criteria andIdentidadNotLike(String value) {
            addCriterion("idEntidad not like", value, "identidad");
            return (Criteria) this;
        }

        public Criteria andIdentidadIn(List<String> values) {
            addCriterion("idEntidad in", values, "identidad");
            return (Criteria) this;
        }

        public Criteria andIdentidadNotIn(List<String> values) {
            addCriterion("idEntidad not in", values, "identidad");
            return (Criteria) this;
        }

        public Criteria andIdentidadBetween(String value1, String value2) {
            addCriterion("idEntidad between", value1, value2, "identidad");
            return (Criteria) this;
        }

        public Criteria andIdentidadNotBetween(String value1, String value2) {
            addCriterion("idEntidad not between", value1, value2, "identidad");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table supervisor_entidad
     *
     * @mbggenerated do_not_delete_during_merge Mon May 01 19:47:25 CDT 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table supervisor_entidad
     *
     * @mbggenerated Mon May 01 19:47:25 CDT 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value) {
            super();
            this.condition = condition;
            this.value = value;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.betweenValue = true;
        }
    }
}