package com.sysdt.lock.model;

public class SupervisorEntidad {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supervisor_entidad.id
     *
     * @mbggenerated Mon May 01 19:47:25 CDT 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supervisor_entidad.idTipoUsuario
     *
     * @mbggenerated Mon May 01 19:47:25 CDT 2017
     */
    private Integer idtipousuario;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supervisor_entidad.username
     *
     * @mbggenerated Mon May 01 19:47:25 CDT 2017
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supervisor_entidad.idTipoEntidad
     *
     * @mbggenerated Mon May 01 19:47:25 CDT 2017
     */
    private Integer idtipoentidad;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supervisor_entidad.idEntidad
     *
     * @mbggenerated Mon May 01 19:47:25 CDT 2017
     */
    private String identidad;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supervisor_entidad.id
     *
     * @return the value of supervisor_entidad.id
     *
     * @mbggenerated Mon May 01 19:47:25 CDT 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supervisor_entidad.id
     *
     * @param id the value for supervisor_entidad.id
     *
     * @mbggenerated Mon May 01 19:47:25 CDT 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supervisor_entidad.idTipoUsuario
     *
     * @return the value of supervisor_entidad.idTipoUsuario
     *
     * @mbggenerated Mon May 01 19:47:25 CDT 2017
     */
    public Integer getIdtipousuario() {
        return idtipousuario;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supervisor_entidad.idTipoUsuario
     *
     * @param idtipousuario the value for supervisor_entidad.idTipoUsuario
     *
     * @mbggenerated Mon May 01 19:47:25 CDT 2017
     */
    public void setIdtipousuario(Integer idtipousuario) {
        this.idtipousuario = idtipousuario;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supervisor_entidad.username
     *
     * @return the value of supervisor_entidad.username
     *
     * @mbggenerated Mon May 01 19:47:25 CDT 2017
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supervisor_entidad.username
     *
     * @param username the value for supervisor_entidad.username
     *
     * @mbggenerated Mon May 01 19:47:25 CDT 2017
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supervisor_entidad.idTipoEntidad
     *
     * @return the value of supervisor_entidad.idTipoEntidad
     *
     * @mbggenerated Mon May 01 19:47:25 CDT 2017
     */
    public Integer getIdtipoentidad() {
        return idtipoentidad;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supervisor_entidad.idTipoEntidad
     *
     * @param idtipoentidad the value for supervisor_entidad.idTipoEntidad
     *
     * @mbggenerated Mon May 01 19:47:25 CDT 2017
     */
    public void setIdtipoentidad(Integer idtipoentidad) {
        this.idtipoentidad = idtipoentidad;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supervisor_entidad.idEntidad
     *
     * @return the value of supervisor_entidad.idEntidad
     *
     * @mbggenerated Mon May 01 19:47:25 CDT 2017
     */
    public String getIdentidad() {
        return identidad;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supervisor_entidad.idEntidad
     *
     * @param identidad the value for supervisor_entidad.idEntidad
     *
     * @mbggenerated Mon May 01 19:47:25 CDT 2017
     */
    public void setIdentidad(String identidad) {
        this.identidad = identidad;
    }
}