package com.sysdt.lock.model;

public class TipoEntidad {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tipo_entidad.id
     *
     * @mbggenerated Mon May 01 19:47:25 CDT 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tipo_entidad.tipo
     *
     * @mbggenerated Mon May 01 19:47:25 CDT 2017
     */
    private String tipo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tipo_entidad.id
     *
     * @return the value of tipo_entidad.id
     *
     * @mbggenerated Mon May 01 19:47:25 CDT 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tipo_entidad.id
     *
     * @param id the value for tipo_entidad.id
     *
     * @mbggenerated Mon May 01 19:47:25 CDT 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tipo_entidad.tipo
     *
     * @return the value of tipo_entidad.tipo
     *
     * @mbggenerated Mon May 01 19:47:25 CDT 2017
     */
    public String getTipo() {
        return tipo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tipo_entidad.tipo
     *
     * @param tipo the value for tipo_entidad.tipo
     *
     * @mbggenerated Mon May 01 19:47:25 CDT 2017
     */
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
}