package com.sysdt.lock.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class UsuarioExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table usuario
     *
     * @mbggenerated Mon May 01 19:47:25 CDT 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table usuario
     *
     * @mbggenerated Mon May 01 19:47:25 CDT 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table usuario
     *
     * @mbggenerated Mon May 01 19:47:25 CDT 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usuario
     *
     * @mbggenerated Mon May 01 19:47:25 CDT 2017
     */
    public UsuarioExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usuario
     *
     * @mbggenerated Mon May 01 19:47:25 CDT 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usuario
     *
     * @mbggenerated Mon May 01 19:47:25 CDT 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usuario
     *
     * @mbggenerated Mon May 01 19:47:25 CDT 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usuario
     *
     * @mbggenerated Mon May 01 19:47:25 CDT 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usuario
     *
     * @mbggenerated Mon May 01 19:47:25 CDT 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usuario
     *
     * @mbggenerated Mon May 01 19:47:25 CDT 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usuario
     *
     * @mbggenerated Mon May 01 19:47:25 CDT 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usuario
     *
     * @mbggenerated Mon May 01 19:47:25 CDT 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usuario
     *
     * @mbggenerated Mon May 01 19:47:25 CDT 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usuario
     *
     * @mbggenerated Mon May 01 19:47:25 CDT 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table usuario
     *
     * @mbggenerated Mon May 01 19:47:25 CDT 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andUsernameIsNull() {
            addCriterion("username is null");
            return (Criteria) this;
        }

        public Criteria andUsernameIsNotNull() {
            addCriterion("username is not null");
            return (Criteria) this;
        }

        public Criteria andUsernameEqualTo(String value) {
            addCriterion("username =", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameNotEqualTo(String value) {
            addCriterion("username <>", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameGreaterThan(String value) {
            addCriterion("username >", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameGreaterThanOrEqualTo(String value) {
            addCriterion("username >=", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameLessThan(String value) {
            addCriterion("username <", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameLessThanOrEqualTo(String value) {
            addCriterion("username <=", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameLike(String value) {
            addCriterion("username like", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameNotLike(String value) {
            addCriterion("username not like", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameIn(List<String> values) {
            addCriterion("username in", values, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameNotIn(List<String> values) {
            addCriterion("username not in", values, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameBetween(String value1, String value2) {
            addCriterion("username between", value1, value2, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameNotBetween(String value1, String value2) {
            addCriterion("username not between", value1, value2, "username");
            return (Criteria) this;
        }

        public Criteria andPasswordIsNull() {
            addCriterion("password is null");
            return (Criteria) this;
        }

        public Criteria andPasswordIsNotNull() {
            addCriterion("password is not null");
            return (Criteria) this;
        }

        public Criteria andPasswordEqualTo(String value) {
            addCriterion("password =", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotEqualTo(String value) {
            addCriterion("password <>", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordGreaterThan(String value) {
            addCriterion("password >", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordGreaterThanOrEqualTo(String value) {
            addCriterion("password >=", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordLessThan(String value) {
            addCriterion("password <", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordLessThanOrEqualTo(String value) {
            addCriterion("password <=", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordLike(String value) {
            addCriterion("password like", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotLike(String value) {
            addCriterion("password not like", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordIn(List<String> values) {
            addCriterion("password in", values, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotIn(List<String> values) {
            addCriterion("password not in", values, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordBetween(String value1, String value2) {
            addCriterion("password between", value1, value2, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotBetween(String value1, String value2) {
            addCriterion("password not between", value1, value2, "password");
            return (Criteria) this;
        }

        public Criteria andEnabledIsNull() {
            addCriterion("enabled is null");
            return (Criteria) this;
        }

        public Criteria andEnabledIsNotNull() {
            addCriterion("enabled is not null");
            return (Criteria) this;
        }

        public Criteria andEnabledEqualTo(Boolean value) {
            addCriterion("enabled =", value, "enabled");
            return (Criteria) this;
        }

        public Criteria andEnabledNotEqualTo(Boolean value) {
            addCriterion("enabled <>", value, "enabled");
            return (Criteria) this;
        }

        public Criteria andEnabledGreaterThan(Boolean value) {
            addCriterion("enabled >", value, "enabled");
            return (Criteria) this;
        }

        public Criteria andEnabledGreaterThanOrEqualTo(Boolean value) {
            addCriterion("enabled >=", value, "enabled");
            return (Criteria) this;
        }

        public Criteria andEnabledLessThan(Boolean value) {
            addCriterion("enabled <", value, "enabled");
            return (Criteria) this;
        }

        public Criteria andEnabledLessThanOrEqualTo(Boolean value) {
            addCriterion("enabled <=", value, "enabled");
            return (Criteria) this;
        }

        public Criteria andEnabledIn(List<Boolean> values) {
            addCriterion("enabled in", values, "enabled");
            return (Criteria) this;
        }

        public Criteria andEnabledNotIn(List<Boolean> values) {
            addCriterion("enabled not in", values, "enabled");
            return (Criteria) this;
        }

        public Criteria andEnabledBetween(Boolean value1, Boolean value2) {
            addCriterion("enabled between", value1, value2, "enabled");
            return (Criteria) this;
        }

        public Criteria andEnabledNotBetween(Boolean value1, Boolean value2) {
            addCriterion("enabled not between", value1, value2, "enabled");
            return (Criteria) this;
        }

        public Criteria andCaducidadpasswordIsNull() {
            addCriterion("caducidadPassword is null");
            return (Criteria) this;
        }

        public Criteria andCaducidadpasswordIsNotNull() {
            addCriterion("caducidadPassword is not null");
            return (Criteria) this;
        }

        public Criteria andCaducidadpasswordEqualTo(Date value) {
            addCriterion("caducidadPassword =", value, "caducidadpassword");
            return (Criteria) this;
        }

        public Criteria andCaducidadpasswordNotEqualTo(Date value) {
            addCriterion("caducidadPassword <>", value, "caducidadpassword");
            return (Criteria) this;
        }

        public Criteria andCaducidadpasswordGreaterThan(Date value) {
            addCriterion("caducidadPassword >", value, "caducidadpassword");
            return (Criteria) this;
        }

        public Criteria andCaducidadpasswordGreaterThanOrEqualTo(Date value) {
            addCriterion("caducidadPassword >=", value, "caducidadpassword");
            return (Criteria) this;
        }

        public Criteria andCaducidadpasswordLessThan(Date value) {
            addCriterion("caducidadPassword <", value, "caducidadpassword");
            return (Criteria) this;
        }

        public Criteria andCaducidadpasswordLessThanOrEqualTo(Date value) {
            addCriterion("caducidadPassword <=", value, "caducidadpassword");
            return (Criteria) this;
        }

        public Criteria andCaducidadpasswordIn(List<Date> values) {
            addCriterion("caducidadPassword in", values, "caducidadpassword");
            return (Criteria) this;
        }

        public Criteria andCaducidadpasswordNotIn(List<Date> values) {
            addCriterion("caducidadPassword not in", values, "caducidadpassword");
            return (Criteria) this;
        }

        public Criteria andCaducidadpasswordBetween(Date value1, Date value2) {
            addCriterion("caducidadPassword between", value1, value2, "caducidadpassword");
            return (Criteria) this;
        }

        public Criteria andCaducidadpasswordNotBetween(Date value1, Date value2) {
            addCriterion("caducidadPassword not between", value1, value2, "caducidadpassword");
            return (Criteria) this;
        }

        public Criteria andIdClienteIsNull() {
            addCriterion("id_cliente is null");
            return (Criteria) this;
        }

        public Criteria andIdClienteIsNotNull() {
            addCriterion("id_cliente is not null");
            return (Criteria) this;
        }

        public Criteria andIdClienteEqualTo(Integer value) {
            addCriterion("id_cliente =", value, "idCliente");
            return (Criteria) this;
        }

        public Criteria andIdClienteNotEqualTo(Integer value) {
            addCriterion("id_cliente <>", value, "idCliente");
            return (Criteria) this;
        }

        public Criteria andIdClienteGreaterThan(Integer value) {
            addCriterion("id_cliente >", value, "idCliente");
            return (Criteria) this;
        }

        public Criteria andIdClienteGreaterThanOrEqualTo(Integer value) {
            addCriterion("id_cliente >=", value, "idCliente");
            return (Criteria) this;
        }

        public Criteria andIdClienteLessThan(Integer value) {
            addCriterion("id_cliente <", value, "idCliente");
            return (Criteria) this;
        }

        public Criteria andIdClienteLessThanOrEqualTo(Integer value) {
            addCriterion("id_cliente <=", value, "idCliente");
            return (Criteria) this;
        }

        public Criteria andIdClienteIn(List<Integer> values) {
            addCriterion("id_cliente in", values, "idCliente");
            return (Criteria) this;
        }

        public Criteria andIdClienteNotIn(List<Integer> values) {
            addCriterion("id_cliente not in", values, "idCliente");
            return (Criteria) this;
        }

        public Criteria andIdClienteBetween(Integer value1, Integer value2) {
            addCriterion("id_cliente between", value1, value2, "idCliente");
            return (Criteria) this;
        }

        public Criteria andIdClienteNotBetween(Integer value1, Integer value2) {
            addCriterion("id_cliente not between", value1, value2, "idCliente");
            return (Criteria) this;
        }

        public Criteria andIdTipousuarioIsNull() {
            addCriterion("id_tipousuario is null");
            return (Criteria) this;
        }

        public Criteria andIdTipousuarioIsNotNull() {
            addCriterion("id_tipousuario is not null");
            return (Criteria) this;
        }

        public Criteria andIdTipousuarioEqualTo(Integer value) {
            addCriterion("id_tipousuario =", value, "idTipousuario");
            return (Criteria) this;
        }

        public Criteria andIdTipousuarioNotEqualTo(Integer value) {
            addCriterion("id_tipousuario <>", value, "idTipousuario");
            return (Criteria) this;
        }

        public Criteria andIdTipousuarioGreaterThan(Integer value) {
            addCriterion("id_tipousuario >", value, "idTipousuario");
            return (Criteria) this;
        }

        public Criteria andIdTipousuarioGreaterThanOrEqualTo(Integer value) {
            addCriterion("id_tipousuario >=", value, "idTipousuario");
            return (Criteria) this;
        }

        public Criteria andIdTipousuarioLessThan(Integer value) {
            addCriterion("id_tipousuario <", value, "idTipousuario");
            return (Criteria) this;
        }

        public Criteria andIdTipousuarioLessThanOrEqualTo(Integer value) {
            addCriterion("id_tipousuario <=", value, "idTipousuario");
            return (Criteria) this;
        }

        public Criteria andIdTipousuarioIn(List<Integer> values) {
            addCriterion("id_tipousuario in", values, "idTipousuario");
            return (Criteria) this;
        }

        public Criteria andIdTipousuarioNotIn(List<Integer> values) {
            addCriterion("id_tipousuario not in", values, "idTipousuario");
            return (Criteria) this;
        }

        public Criteria andIdTipousuarioBetween(Integer value1, Integer value2) {
            addCriterion("id_tipousuario between", value1, value2, "idTipousuario");
            return (Criteria) this;
        }

        public Criteria andIdTipousuarioNotBetween(Integer value1, Integer value2) {
            addCriterion("id_tipousuario not between", value1, value2, "idTipousuario");
            return (Criteria) this;
        }

        public Criteria andNombreIsNull() {
            addCriterion("nombre is null");
            return (Criteria) this;
        }

        public Criteria andNombreIsNotNull() {
            addCriterion("nombre is not null");
            return (Criteria) this;
        }

        public Criteria andNombreEqualTo(String value) {
            addCriterion("nombre =", value, "nombre");
            return (Criteria) this;
        }

        public Criteria andNombreNotEqualTo(String value) {
            addCriterion("nombre <>", value, "nombre");
            return (Criteria) this;
        }

        public Criteria andNombreGreaterThan(String value) {
            addCriterion("nombre >", value, "nombre");
            return (Criteria) this;
        }

        public Criteria andNombreGreaterThanOrEqualTo(String value) {
            addCriterion("nombre >=", value, "nombre");
            return (Criteria) this;
        }

        public Criteria andNombreLessThan(String value) {
            addCriterion("nombre <", value, "nombre");
            return (Criteria) this;
        }

        public Criteria andNombreLessThanOrEqualTo(String value) {
            addCriterion("nombre <=", value, "nombre");
            return (Criteria) this;
        }

        public Criteria andNombreLike(String value) {
            addCriterion("nombre like", value, "nombre");
            return (Criteria) this;
        }

        public Criteria andNombreNotLike(String value) {
            addCriterion("nombre not like", value, "nombre");
            return (Criteria) this;
        }

        public Criteria andNombreIn(List<String> values) {
            addCriterion("nombre in", values, "nombre");
            return (Criteria) this;
        }

        public Criteria andNombreNotIn(List<String> values) {
            addCriterion("nombre not in", values, "nombre");
            return (Criteria) this;
        }

        public Criteria andNombreBetween(String value1, String value2) {
            addCriterion("nombre between", value1, value2, "nombre");
            return (Criteria) this;
        }

        public Criteria andNombreNotBetween(String value1, String value2) {
            addCriterion("nombre not between", value1, value2, "nombre");
            return (Criteria) this;
        }

        public Criteria andApaternoIsNull() {
            addCriterion("apaterno is null");
            return (Criteria) this;
        }

        public Criteria andApaternoIsNotNull() {
            addCriterion("apaterno is not null");
            return (Criteria) this;
        }

        public Criteria andApaternoEqualTo(String value) {
            addCriterion("apaterno =", value, "apaterno");
            return (Criteria) this;
        }

        public Criteria andApaternoNotEqualTo(String value) {
            addCriterion("apaterno <>", value, "apaterno");
            return (Criteria) this;
        }

        public Criteria andApaternoGreaterThan(String value) {
            addCriterion("apaterno >", value, "apaterno");
            return (Criteria) this;
        }

        public Criteria andApaternoGreaterThanOrEqualTo(String value) {
            addCriterion("apaterno >=", value, "apaterno");
            return (Criteria) this;
        }

        public Criteria andApaternoLessThan(String value) {
            addCriterion("apaterno <", value, "apaterno");
            return (Criteria) this;
        }

        public Criteria andApaternoLessThanOrEqualTo(String value) {
            addCriterion("apaterno <=", value, "apaterno");
            return (Criteria) this;
        }

        public Criteria andApaternoLike(String value) {
            addCriterion("apaterno like", value, "apaterno");
            return (Criteria) this;
        }

        public Criteria andApaternoNotLike(String value) {
            addCriterion("apaterno not like", value, "apaterno");
            return (Criteria) this;
        }

        public Criteria andApaternoIn(List<String> values) {
            addCriterion("apaterno in", values, "apaterno");
            return (Criteria) this;
        }

        public Criteria andApaternoNotIn(List<String> values) {
            addCriterion("apaterno not in", values, "apaterno");
            return (Criteria) this;
        }

        public Criteria andApaternoBetween(String value1, String value2) {
            addCriterion("apaterno between", value1, value2, "apaterno");
            return (Criteria) this;
        }

        public Criteria andApaternoNotBetween(String value1, String value2) {
            addCriterion("apaterno not between", value1, value2, "apaterno");
            return (Criteria) this;
        }

        public Criteria andAmaternoIsNull() {
            addCriterion("amaterno is null");
            return (Criteria) this;
        }

        public Criteria andAmaternoIsNotNull() {
            addCriterion("amaterno is not null");
            return (Criteria) this;
        }

        public Criteria andAmaternoEqualTo(String value) {
            addCriterion("amaterno =", value, "amaterno");
            return (Criteria) this;
        }

        public Criteria andAmaternoNotEqualTo(String value) {
            addCriterion("amaterno <>", value, "amaterno");
            return (Criteria) this;
        }

        public Criteria andAmaternoGreaterThan(String value) {
            addCriterion("amaterno >", value, "amaterno");
            return (Criteria) this;
        }

        public Criteria andAmaternoGreaterThanOrEqualTo(String value) {
            addCriterion("amaterno >=", value, "amaterno");
            return (Criteria) this;
        }

        public Criteria andAmaternoLessThan(String value) {
            addCriterion("amaterno <", value, "amaterno");
            return (Criteria) this;
        }

        public Criteria andAmaternoLessThanOrEqualTo(String value) {
            addCriterion("amaterno <=", value, "amaterno");
            return (Criteria) this;
        }

        public Criteria andAmaternoLike(String value) {
            addCriterion("amaterno like", value, "amaterno");
            return (Criteria) this;
        }

        public Criteria andAmaternoNotLike(String value) {
            addCriterion("amaterno not like", value, "amaterno");
            return (Criteria) this;
        }

        public Criteria andAmaternoIn(List<String> values) {
            addCriterion("amaterno in", values, "amaterno");
            return (Criteria) this;
        }

        public Criteria andAmaternoNotIn(List<String> values) {
            addCriterion("amaterno not in", values, "amaterno");
            return (Criteria) this;
        }

        public Criteria andAmaternoBetween(String value1, String value2) {
            addCriterion("amaterno between", value1, value2, "amaterno");
            return (Criteria) this;
        }

        public Criteria andAmaternoNotBetween(String value1, String value2) {
            addCriterion("amaterno not between", value1, value2, "amaterno");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table usuario
     *
     * @mbggenerated do_not_delete_during_merge Mon May 01 19:47:25 CDT 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table usuario
     *
     * @mbggenerated Mon May 01 19:47:25 CDT 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value) {
            super();
            this.condition = condition;
            this.value = value;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.betweenValue = true;
        }
    }
}