package com.sysdt.lock.model;

import java.util.Date;

public class Usuario {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usuario.username
     *
     * @mbggenerated Fri Apr 14 21:13:50 CDT 2017
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usuario.password
     *
     * @mbggenerated Fri Apr 14 21:13:50 CDT 2017
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usuario.enabled
     *
     * @mbggenerated Fri Apr 14 21:13:50 CDT 2017
     */
    private Boolean enabled;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usuario.caducidadPassword
     *
     * @mbggenerated Fri Apr 14 21:13:50 CDT 2017
     */
    private Date caducidadpassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usuario.id_cliente
     *
     * @mbggenerated Fri Apr 14 21:13:50 CDT 2017
     */
    private Integer idCliente;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usuario.id_tipousuario
     *
     * @mbggenerated Fri Apr 14 21:13:50 CDT 2017
     */
    private Integer idTipousuario;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usuario.username
     *
     * @return the value of usuario.username
     *
     * @mbggenerated Fri Apr 14 21:13:50 CDT 2017
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usuario.username
     *
     * @param username the value for usuario.username
     *
     * @mbggenerated Fri Apr 14 21:13:50 CDT 2017
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usuario.password
     *
     * @return the value of usuario.password
     *
     * @mbggenerated Fri Apr 14 21:13:50 CDT 2017
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usuario.password
     *
     * @param password the value for usuario.password
     *
     * @mbggenerated Fri Apr 14 21:13:50 CDT 2017
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usuario.enabled
     *
     * @return the value of usuario.enabled
     *
     * @mbggenerated Fri Apr 14 21:13:50 CDT 2017
     */
    public Boolean getEnabled() {
        return enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usuario.enabled
     *
     * @param enabled the value for usuario.enabled
     *
     * @mbggenerated Fri Apr 14 21:13:50 CDT 2017
     */
    public void setEnabled(Boolean enabled) {
        this.enabled = enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usuario.caducidadPassword
     *
     * @return the value of usuario.caducidadPassword
     *
     * @mbggenerated Fri Apr 14 21:13:50 CDT 2017
     */
    public Date getCaducidadpassword() {
        return caducidadpassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usuario.caducidadPassword
     *
     * @param caducidadpassword the value for usuario.caducidadPassword
     *
     * @mbggenerated Fri Apr 14 21:13:50 CDT 2017
     */
    public void setCaducidadpassword(Date caducidadpassword) {
        this.caducidadpassword = caducidadpassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usuario.id_cliente
     *
     * @return the value of usuario.id_cliente
     *
     * @mbggenerated Fri Apr 14 21:13:50 CDT 2017
     */
    public Integer getIdCliente() {
        return idCliente;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usuario.id_cliente
     *
     * @param idCliente the value for usuario.id_cliente
     *
     * @mbggenerated Fri Apr 14 21:13:50 CDT 2017
     */
    public void setIdCliente(Integer idCliente) {
        this.idCliente = idCliente;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usuario.id_tipousuario
     *
     * @return the value of usuario.id_tipousuario
     *
     * @mbggenerated Fri Apr 14 21:13:50 CDT 2017
     */
    public Integer getIdTipousuario() {
        return idTipousuario;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usuario.id_tipousuario
     *
     * @param idTipousuario the value for usuario.id_tipousuario
     *
     * @mbggenerated Fri Apr 14 21:13:50 CDT 2017
     */
    public void setIdTipousuario(Integer idTipousuario) {
        this.idTipousuario = idTipousuario;
    }
}