package com.sysdt.lock.model;

import java.util.Date;

public class Usuario {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usuario.username
     *
     * @mbggenerated Mon May 01 19:47:25 CDT 2017
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usuario.password
     *
     * @mbggenerated Mon May 01 19:47:25 CDT 2017
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usuario.enabled
     *
     * @mbggenerated Mon May 01 19:47:25 CDT 2017
     */
    private Boolean enabled;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usuario.caducidadPassword
     *
     * @mbggenerated Mon May 01 19:47:25 CDT 2017
     */
    private Date caducidadpassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usuario.id_cliente
     *
     * @mbggenerated Mon May 01 19:47:25 CDT 2017
     */
    private Integer idCliente;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usuario.id_tipousuario
     *
     * @mbggenerated Mon May 01 19:47:25 CDT 2017
     */
    private Integer idTipousuario;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usuario.nombre
     *
     * @mbggenerated Mon May 01 19:47:25 CDT 2017
     */
    private String nombre;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usuario.apaterno
     *
     * @mbggenerated Mon May 01 19:47:25 CDT 2017
     */
    private String apaterno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usuario.amaterno
     *
     * @mbggenerated Mon May 01 19:47:25 CDT 2017
     */
    private String amaterno;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usuario.username
     *
     * @return the value of usuario.username
     *
     * @mbggenerated Mon May 01 19:47:25 CDT 2017
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usuario.username
     *
     * @param username the value for usuario.username
     *
     * @mbggenerated Mon May 01 19:47:25 CDT 2017
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usuario.password
     *
     * @return the value of usuario.password
     *
     * @mbggenerated Mon May 01 19:47:25 CDT 2017
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usuario.password
     *
     * @param password the value for usuario.password
     *
     * @mbggenerated Mon May 01 19:47:25 CDT 2017
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usuario.enabled
     *
     * @return the value of usuario.enabled
     *
     * @mbggenerated Mon May 01 19:47:25 CDT 2017
     */
    public Boolean getEnabled() {
        return enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usuario.enabled
     *
     * @param enabled the value for usuario.enabled
     *
     * @mbggenerated Mon May 01 19:47:25 CDT 2017
     */
    public void setEnabled(Boolean enabled) {
        this.enabled = enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usuario.caducidadPassword
     *
     * @return the value of usuario.caducidadPassword
     *
     * @mbggenerated Mon May 01 19:47:25 CDT 2017
     */
    public Date getCaducidadpassword() {
        return caducidadpassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usuario.caducidadPassword
     *
     * @param caducidadpassword the value for usuario.caducidadPassword
     *
     * @mbggenerated Mon May 01 19:47:25 CDT 2017
     */
    public void setCaducidadpassword(Date caducidadpassword) {
        this.caducidadpassword = caducidadpassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usuario.id_cliente
     *
     * @return the value of usuario.id_cliente
     *
     * @mbggenerated Mon May 01 19:47:25 CDT 2017
     */
    public Integer getIdCliente() {
        return idCliente;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usuario.id_cliente
     *
     * @param idCliente the value for usuario.id_cliente
     *
     * @mbggenerated Mon May 01 19:47:25 CDT 2017
     */
    public void setIdCliente(Integer idCliente) {
        this.idCliente = idCliente;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usuario.id_tipousuario
     *
     * @return the value of usuario.id_tipousuario
     *
     * @mbggenerated Mon May 01 19:47:25 CDT 2017
     */
    public Integer getIdTipousuario() {
        return idTipousuario;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usuario.id_tipousuario
     *
     * @param idTipousuario the value for usuario.id_tipousuario
     *
     * @mbggenerated Mon May 01 19:47:25 CDT 2017
     */
    public void setIdTipousuario(Integer idTipousuario) {
        this.idTipousuario = idTipousuario;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usuario.nombre
     *
     * @return the value of usuario.nombre
     *
     * @mbggenerated Mon May 01 19:47:25 CDT 2017
     */
    public String getNombre() {
        return nombre;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usuario.nombre
     *
     * @param nombre the value for usuario.nombre
     *
     * @mbggenerated Mon May 01 19:47:25 CDT 2017
     */
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usuario.apaterno
     *
     * @return the value of usuario.apaterno
     *
     * @mbggenerated Mon May 01 19:47:25 CDT 2017
     */
    public String getApaterno() {
        return apaterno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usuario.apaterno
     *
     * @param apaterno the value for usuario.apaterno
     *
     * @mbggenerated Mon May 01 19:47:25 CDT 2017
     */
    public void setApaterno(String apaterno) {
        this.apaterno = apaterno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usuario.amaterno
     *
     * @return the value of usuario.amaterno
     *
     * @mbggenerated Mon May 01 19:47:25 CDT 2017
     */
    public String getAmaterno() {
        return amaterno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usuario.amaterno
     *
     * @param amaterno the value for usuario.amaterno
     *
     * @mbggenerated Mon May 01 19:47:25 CDT 2017
     */
    public void setAmaterno(String amaterno) {
        this.amaterno = amaterno;
    }
}